import { compileFromFile } from 'json-schema-to-typescript';
import { writeFileSync } from 'fs';

const style = {
  bracketSpacing: false,
  printWidth: 120,
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: 'es5',
  useTabs: false,
};
const bannerComment = `/* eslint-disable */
/**
* This file was automatically generated by schemar and json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the underlying Rust types in \`src/model.rs\`,
* and run \`./gen-ts.sh\` to regenerate this file.
*/`;

const args = process.argv.slice(2);
if (args.length !== 2) {
  console.log('Usage: node gen-ts.js <schema>.json <out>.d.ts');
  process.exit(1);
}

compileFromFile(args[0], {
  style,
  bannerComment,
}).then((ts) => writeFileSync(args[1], ts));
