/* eslint-disable */
/**
 * This file was automatically generated by schemar and json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the underlying Rust types in `src/model.rs`,
 * and run `./gen-ts.sh` to regenerate this file.
 */

export interface Person {
  name: string;
  [k: string]: unknown;
}
