/* eslint-disable */
/**
 * This file was automatically generated by schemar and json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the underlying Rust types in `src/model.rs`,
 * and run `./gen-ts.sh` to regenerate this file.
 */

export type Fact =
  | {
      Birth: {
        date: number;
        [k: string]: unknown;
      };
    }
  | {
      Death: {
        date: number;
        [k: string]: unknown;
      };
    }
  | {
      Job: string;
    };

export interface Person {
  facts: Fact[];
  name: string;
  [k: string]: unknown;
}
